
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/crudtest
    username: root
    password: maria
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true

server:
  port: 9003

logging:
  level:
    com.spring.toyproject: DEBUG
    # SQL ??
    org.hibernate.SQL: DEBUG
    # ?? ???? ????
    org.springframework.web: DEBUG
    # SQL ???? ??? ??
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


# jwt setting
jwt:
  # secret key (?? ????? ????? ??)
  secret: iSCkPmXVv5n1n0kMr6A0oh0ATuI9PG9zjeRJUV9KfzM=
  # ???? (???) - 24??
  expiration: 86400000



# ?? ??? ?? ?? ??
file:
  upload:
    location: ${user.home}/travels/uploads/